server:
  port: 8002
  #servlet:
  #默认没有项目名，你可以加
   # context-path: /demo-customer
spring:
  application:
    name: order

eureka:
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 10000  #清理间隔（毫秒）
    #peerNodeReadTimeoutMs: 200000
    #peerNodeConnectTimeoutMs: 60000
    #https://blog.csdn.net/qq_26440803/article/details/83113037
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id
    lease-expiration-duration-in-seconds: 8   #续约更新时间间隔
    lease-renewal-interval-in-seconds: 20     #续约到期时间间隔，默认90
  client:
    registerWithEureka: true  #是否注册自己到eureka服务中，默认不注册
    fetchRegistry: true     #是否从eureka服务中获取注册信息
    serviceUrl:
      # 服务器注册/获取服务器的zone
      #自己注册到eureka那个服务,可注册多个，用，分隔
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/
    eurekaServerConnectTimeoutSeconds: 60
    eurekaServerReadTimeoutSeconds: 60
    # 健康检测问题 https://my.oschina.net/andChow/blog/1939238

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 2000
        read-timeout: 2000

###设置feign客户端超时时间,记得在调用方接口上加@LoadBalanced, 这是另一种方式
###SpringCloud feign 默认开启支持ribbon
#ribbon:
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  #ReadTimeout: 5000
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  #ConnectTimeout: 5000




