server:
  port: 8010
spring:
  application:
    name: shardingjdbc

sharding:
  jdbc:
  ####ds1
    datasource:
      names: ds1
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test01?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: Alex2017!
####  分片配置
    config:
      sharding:
        tables:
        ####t_order表分破案策略
          t_order:
            table-strategy:
              inline:
              #### 根据userid 进行分片
                sharding-column: user_id
               ####  ds_1.t_order_0 ds_1.t_order_1
                algorithm-expression: ds_1.t_order_$->{user_id % 2}
              ###分表的总数 0到1   t_order_0 t_order_1
            actual-data-nodes: ds1.t_order_$->{0..1}
        props:
          sql:
          ### 开启分片日志
            show: true

#sql logs
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  config-locations: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
     com.mgp.*.dao : debug

eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id
    lease-expiration-duration-in-seconds: 20   #续约更新时间间隔
    lease-renewal-interval-in-seconds: 60     #续约到期时间间隔，默认90
  client:
    registerWithEureka: true  #是否注册自己到eureka服务中，默认不注册
    fetchRegistry: true     #是否从eureka服务中获取注册信息
    serviceUrl:
      # 服务器注册/获取服务器的zone
      #自己注册到eureka那个服务,可注册多个，用，分隔
      defaultZone: http://${eureka.instance.hostname}:8001/eureka/
    eurekaServerConnectTimeoutSeconds: 60
    eurekaServerReadTimeoutSeconds: 60
    # 健康检测问题 https://my.oschina.net/andChow/blog/1939238



