spring:
  application:
    name: springboot2-eureka

server:
  port: 8001

eureka:
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 10000  #清理间隔（毫秒）
    #peerNodeReadTimeoutMs: 200000
    #peerNodeConnectTimeoutMs: 60000
    #https://blog.csdn.net/qq_26440803/article/details/83113037
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port} #指定实例id
    lease-expiration-duration-in-seconds: 5   #续约更新时间间隔
    lease-renewal-interval-in-seconds: 10     #心跳时间，默认90
  client:
    #因为自己是注册中心，是否需要将自己注册给自己的注册中心（集群的时候是需要是为true）
    registerWithEureka: false  #是否注册自己到eureka服务中，默认不注册
    ###因为自己是注册中心， 不需要去检索服务信息
    fetchRegistry: false     #是否从eureka服务中获取注册信息
    serviceUrl:
      # 服务器注册/获取服务器的zone
      #自己注册到eureka那个服务,可注册多个，用，分隔
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    eurekaServerConnectTimeoutSeconds: 60
    eurekaServerReadTimeoutSeconds: 60
    # 健康检测问题 https://my.oschina.net/andChow/blog/1939238